package vista;

import controlador.Funciones;
import controlador.FuncionesLaboratorio;
import java.awt.Component;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import modelo.Laboratorios;

/**
 * @web http://www.diegoacuario.blogspot.com
 * @author diegoacuario
 */
public class RegistraLaboratorio extends javax.swing.JDialog {

    private final MenuAdministrador m;
    private final Funciones f;
    private final FuncionesLaboratorio fl;
    private Laboratorios lab;

    /**
     * Creates new form RegistraLaboratorio
     *
     * @param parent
     * @param modal
     * @param m
     */
    public RegistraLaboratorio(java.awt.Frame parent, boolean modal, MenuAdministrador m) {
        super(parent, modal);
        this.m = m;
        this.setUndecorated(true);//quita bordes a jframe
        f = new Funciones();
        lab = new Laboratorios();
        initComponents();
        fl = new FuncionesLaboratorio();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita cerra jframe con ALT+C

        this.setAlwaysOnTop(true);//siempre al frente       
        //nueva instancia de Bloquea pasando como parametros e este JFrame

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel1, gridBagConstraints);

        txtCod.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(txtCod, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descripción: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel3, gridBagConstraints);

        txtNom.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(txtNom, gridBagConstraints);

        btnGuardar.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 2;
        jPanel1.add(btnGuardar, gridBagConstraints);

        txtDes.setColumns(20);
        txtDes.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtDes.setRows(5);
        txtDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.weighty = 0.6;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jButton3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(872, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed

    }//GEN-LAST:event_txtCodActionPerformed

    private void txtCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyTyped
        if (txtCod.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String reg, men = "guardados", men1 = "guardar";
        try {
            if (btnGuardar.getText().equals("Guardar")) {
                reg = fl.registrarLaboratorio(Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web") + "webresources/modelo.laboratorios/registro/",
                        txtCod.getText(), txtNom.getText(), txtDes.getText());
            } else {
                men = "actualizados";
                men1 = "actualizar";
                reg = fl.editarLaboratorio(
                        Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web") + "webresources/modelo.laboratorios/editar/",
                        lab.getIdLaboratorio(),
                        txtCod.getText(),
                        txtNom.getText(),
                        txtDes.getText());
            }

        } catch (Exception ex) {
            reg = "false";
        }
        switch (reg) {
            case "true":
                int x = JOptionPane.showConfirmDialog(rootPane, "Datos " + men + " correctamente,"
                        + "\ndesea salir de la administración de laboratorios.");
                if (x == 0) {
                    dispose();
                    if (m != null) {
                        m.setVisible(true);
                    }
                } else {
                    ((Component) evt.getSource()).transferFocus();
                }
                break;
            case "false":
                int y = JOptionPane.showConfirmDialog(rootPane, "No se pudo " + men1 + " la información,"
                        + "\ndesea salir de la administración de laboratorios.");
                if (y == 0) {
                    dispose();
                    if (m != null) {
                        m.setVisible(true);
                    }
                } else {
                    ((Component) evt.getSource()).transferFocus();
                }
                break;
            default:
                System.out.println(reg);
                break;
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        if (m != null) {
            m.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyReleased
        char c = evt.getKeyChar();
        String cod = txtCod.getText();
        if (c == 10) {
            lab = fl.obtieneDatosLaboratorio(f.obtieneJsonGet(Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web") + "webresources/modelo.laboratorios/cod=" + cod));
            if (lab != null) {
                btnGuardar.setText("Actualizar");
                txtDes.setText(lab.getDescripcion());
                txtNom.setText(lab.getNombre());
            } else {
                btnGuardar.setText("Guardar");
                txtDes.setText("");
                txtNom.setText("");
            }
        }
    }//GEN-LAST:event_txtCodKeyReleased

    private void txtDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesKeyTyped
        if (txtCod.getText().length() >= 255) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDesKeyTyped

    private void txtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyTyped
        if (txtCod.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNomKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
