/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Funciones;
import controlador.FuncionesUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import modelo.Usuarios;

/**
 *
 * @author AYLEEN ROMERO PATIÑO
 */
public class RegistraUsuario extends javax.swing.JDialog {

    private Usuarios u;
    private MenuAdministrador m;
    private final Funciones f;
    private final FuncionesUsuario fUser;
    private Usuarios user;

    /**
     * Creates new form RegistraPersona
     *
     * @param parent
     * @param modal
     * @param m
     * @param u
     */
    public RegistraUsuario(java.awt.Frame parent, boolean modal, MenuAdministrador m, Usuarios u) {
        super(parent, modal);
        this.u = u;
        user = u;
        this.m = m;
        initComponents();
        if (m == null && u != null) {
            jCheckBox1.setVisible(false);
            txtCedula.setText(u.getCedula());
            txtCedula.setEditable(false);
            txtNombres.setText(u.getNombres());
            txtNombres.setEditable(false);
            txtApellidos.setText(u.getApellidos());
            txtApellidos.setEditable(false);
            txtClave.setText(u.getClave());
            txtCelular.setText(u.getCelular());
            txtCorreo.setText(u.getCorreo());
            btnGuardar.setText("Actualizar");
        }
        if (m == null && u == null) {
            jCheckBox1.setVisible(false);
        }
        f = new Funciones();
        fUser = new FuncionesUsuario();
        this.setUndecorated(true);//quita bordes a jframe

        btnEli.setVisible(false);

        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita cerra jframe con ALT+C
        this.setAlwaysOnTop(true);//siempre al frente       
        //nueva instancia de Bloquea pasando como parametros e este JFrame

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEli = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cédula: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel1, gridBagConstraints);

        txtCedula.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(txtCedula, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombres: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel2, gridBagConstraints);

        txtApellidos.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(txtApellidos, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellidos: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel3, gridBagConstraints);

        txtNombres.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(txtNombres, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Correo: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel4, gridBagConstraints);

        txtCorreo.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(txtCorreo, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Clave: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel5, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jButton1, gridBagConstraints);

        btnEli.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        btnEli.setText("Eliminar");
        btnEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(btnEli, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Celular: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel6, gridBagConstraints);

        txtCelular.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(txtCelular, gridBagConstraints);

        txtClave.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtClave, gridBagConstraints);

        btnGuardar.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(btnGuardar, gridBagConstraints);

        jCheckBox1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jCheckBox1.setText("Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jCheckBox1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(737, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        if (m != null) {
            m.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char c = evt.getKeyChar();
        c = (c + "").toLowerCase().charAt(0);
        if ((c < 'a' || c > 'z') && c != 'ñ' && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        char c = evt.getKeyChar();
        c = (c + "").toLowerCase().charAt(0);
        if ((c < 'a' || c > 'z') && c != 'ñ' && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        String val = txtCorreo.getText();
        txtCorreo.setText(val.toLowerCase());
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String reg, men = "guardados", men1 = "guardar";
        int x = 0;
        if (jCheckBox1.isSelected()) {
            x = 1;
        }
        try {
            if (btnGuardar.getText().equals("Actualizar")) {
                reg = fUser.editarUsuario(Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web") + "webresources/modelo.usuarios/editar/",
                        user.getIdUsuario(),
                        txtCedula.getText(), txtClave.getText(), txtNombres.getText(),
                        txtApellidos.getText(), txtCorreo.getText(), txtCelular.getText(), x);

                men = "actualizados";
                men1 = "actualizar";
            } else {

                reg = fUser.registrarUsuario(Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web") + "webresources/modelo.usuarios/registro/",
                        txtCedula.getText(), txtClave.getText(), txtNombres.getText(),
                        txtApellidos.getText(), txtCorreo.getText(), txtCelular.getText(), x);
            }

            if (reg.equals("true")) {
                JOptionPane.showMessageDialog(rootPane, "Datos " + men + " correctamente");
                dispose();
                if (m != null) {
                    m.setVisible(true);
                }
            } else {
                reg = "false";
            }

        } catch (Exception ex) {
            reg = "false";
        }
        if (reg.equals("false")) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo " + men1 + " la información");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        if (u != null) {
            String ced = txtCedula.getText();
            if (ced.length() == 10) {
                boolean x = false;

                String url = Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web") + "webresources/modelo.usuarios/cedula=" + ced;
                user = fUser.obtieneDatosUsuario(f.obtieneJson(url));
                if (user != null && m != null) {
                    if (user.getRolUsuario() == 1) {
                        x = true;
                    }
                    btnEli.setVisible(true);
                    jCheckBox1.setSelected(x);
                    txtNombres.setText(user.getNombres());
                    txtApellidos.setText(user.getApellidos());
                    txtClave.setText(user.getClave());
                    txtCelular.setText(user.getCelular());
                    txtCorreo.setText(user.getCorreo());
                    btnGuardar.setText("Actualizar");
                } else {
                    btnEli.setVisible(false);
                }
            } else {
                jCheckBox1.setSelected(false);
                btnGuardar.setText("Guardar");
                btnEli.setVisible(false);
                txtNombres.setText("");
                txtApellidos.setText("");
                txtClave.setText("");
                txtCelular.setText("");
                txtCorreo.setText("");
            }
        }

    }//GEN-LAST:event_txtCedulaKeyReleased

    private void btnEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliActionPerformed
        int x = JOptionPane.showConfirmDialog(rootPane, "Seguro desea eliminar el usuario:\n" + user.getNombres() + " " + user.getApellidos());
        int y = -1;
        if (x == 0) {
            if (u.getCedula().equals(user.getCedula())) {
                x = JOptionPane.showConfirmDialog(rootPane, "Seguro desea eliminar su propio usuario");
                y = x;
            }
            if (x == 0) {
                String url = Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web"
                ) + "webresources/modelo.usuarios/eliminar/" + user.getIdUsuario();
                String val = f.obtieneTexto(url);
                if (val.equals("true")) {
                    JOptionPane.showMessageDialog(rootPane, "Usuario eliminado correctamente");
                    if (y == x) {
                        dispose();
                        if (m != null) {
                            new Login().setVisible(true);
                            m.dispose();
                        }
                    }
                    btnEli.setVisible(false);
                    txtNombres.setText("");
                    txtApellidos.setText("");
                    txtClave.setText("");
                    txtCelular.setText("");
                    txtCorreo.setText("");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar el usuario");
                }
            }

        }
    }//GEN-LAST:event_btnEliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEli;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
