package vista;

import controlador.Funciones;
import controlador.FuncionesLaboratorio;
import modelo.Bloquea;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modelo.Laboratorios;
import modelo.Usuarios;

/**
 * @web http://www.diegoacuario.blogspot.com
 * @author diegoacuario
 */
public class SeleccioneLaboratorio extends javax.swing.JFrame {

    private Laboratorios l;
    private final Usuarios u;
    private final Funciones f;
    private final FuncionesLaboratorio fl;
   
    /**
     * Creates new form SeleccioneLaboratorio
     *
     * @param u
     */
    public SeleccioneLaboratorio(Usuarios u) {
        this.u = u;
        this.setUndecorated(true);//quita bordes a jframe
        initComponents();
        f = new Funciones();
        fl = new FuncionesLaboratorio();
        lblNombre.setText(lblNombre.getText() + u.getNombres() + " " + u.getApellidos());
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//evita cerra jframe con ALT+C
        this.setExtendedState(MAXIMIZED_BOTH);//maximizado
        this.setAlwaysOnTop(true);//siempre al frente       
        //nueva instancia de Bloquea pasando como parametros e este JFrame
        new Bloquea(this).block();
        Laboratorios lab[] = fl.arrayToMatriz(fl.obtieneDatosLaboratorios(f.obtieneJsonGet(Funciones.getFileProperties("classes/confi.properties").getProperty("servicio_web") + "webresources/modelo.laboratorios/")));
        int filas = 4;
        int colExtra = 1;
        if (lab.length % 4 == 0) {
            colExtra = 0;
        }
        int col = (int) (lab.length / 4.0f) + colExtra;
        int res = 4 - (filas * col) + lab.length;
        int can = 0;
        JButton laboratorios[][] = new JButton[filas][col];
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < col; j++) {
                if (j < col - 1 || (j == col - 1 && i < res)) {
                    laboratorios[i][j] = new JButton();
                    laboratorios[i][j].setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
                    laboratorios[i][j].setText(lab[can].getIdLaboratorio() + ":Lab" + (can + 1) + ": " + lab[can].getCodigo());
                    laboratorios[i][j].setSize(200, 300);
                    laboratorios[i][j].setToolTipText(lab[can].getNombre() + ": " + lab[can].getDescripcion());
                    laboratorios[i][j].setBackground(Color.green);
                    can++;
                    jPanel2.add(laboratorios[i][j]);
                    laboratorios[i][j].addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent evt) {
                            SeleccioneLaboratorio.this.ejecutarAlPresionarBoton(evt);
                        }
                    });
                }
            }
        }
                jPanel2.setLayout(new java.awt.GridLayout(filas, col, 10, 10));
            }

    private void ejecutarAlPresionarBoton(java.awt.event.ActionEvent evt) {
        JButton boton = (JButton) evt.getSource();
        if (boton.getBackground().equals(Color.green)) {
            l = new Laboratorios(Integer.parseInt(boton.getText().split(":")[0]), boton.getToolTipText().split(": ")[0], boton.getText().split(": ")[1], boton.getToolTipText().split(": ")[1],0);
            SeleccioneEquipo e = new SeleccioneEquipo(l, u);
            e.setVisible(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione el laboratorio al que desea acceder");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 100);
        jPanel1.add(jLabel1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jButton1, gridBagConstraints);

        lblNombre.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Bienvenido(a): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 82, 0, 82);
        jPanel1.add(lblNombre, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 951, 502);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Login(0).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
